version: "3.8"
services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: yasser
      MYSQL_USER: yasser
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - back-tier

  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=yasser
      - PMA_PASSWORD=""
      - PMA_PORT=3306
    depends_on:
      - mysql
    ports:
      - "8888:80"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
    networks:
      - back-tier

  backend:
    build:
      context: ./services/api/
      dockerfile: Dockerfile
    working_dir: /var/www/backend
    volumes:
      - ./../backend:/var/www/backend
    depends_on:
      - mysql
      - redis
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - back-tier

  # frontend:
  #   build:
  #     context: ./services/vue/
  #     dockerfile: Dockerfile
  #   working_dir: /var/www/frontend
  #   volumes:
  #     - ./../frontend:/var/www/frontend
  #   expose:
  #     - 3000
  #   # ports:
  #   #   - "3000:3000"
  #   networks:
  #     - back-tier

  nginx:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./../frontend:/var/www/frontend
      - ./../backend:/var/www/backend
      - ./services/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      # - frontend
    ports:
      - "8088:80"
    networks:
      - back-tier

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  back-tier:
    driver: bridge
